# Generated by Django 4.2 on 2025-10-29 17:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('cartao', 'Cartão de Crédito'), ('emprestimo', 'Empréstimo'), ('compra', 'Compra Parcelada'), ('outro', 'Outros')], default='compra', max_length=20)),
                ('forma_pagamento', models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Débito em Conta'), ('boleto', 'Boleto'), ('pix', 'Pix'), ('outro', 'Outro')], default='credito', max_length=20)),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas_totais', models.PositiveIntegerField(default=1)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('quitada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paga', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='dividas.divida')),
            ],
        ),
    ]
