# Generated by Django 4.2 on 2025-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='tipo_despesa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
