# Generated by Django 4.2 on 2025-10-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividas', '0002_divida_tipo_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='divida',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divida',
            name='mes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
