# Generated by Django 4.2 on 2025-10-26 23:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPilar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(help_text='Nome da categoria', max_length=100, unique=True)),
                ('pilar', models.CharField(choices=[('NECESSIDADE', 'Necessidade'), ('CONFORTO & EXPERIÊNCIA', 'Conforto & Experiência'), ('CRESCIMENTO & LIBERDADE', 'Crescimento & Liberdade')], max_length=50)),
                ('palavras_chave', models.TextField(blank=True, help_text='Palavras-chave separadas por vírgula para identificação automática')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria Pilar',
                'verbose_name_plural': 'Categorias Pilar',
            },
        ),
        migrations.CreateModel(
            name='ImportacaoLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='importacoes/')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Parcial')], max_length=20)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_importados', models.IntegerField(default=0)),
                ('registros_duplicados', models.IntegerField(default=0)),
                ('registros_rejeitados', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de Importação',
                'verbose_name_plural': 'Logs de Importação',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(help_text='Data do lançamento (YYYY-MM-DD)')),
                ('mes', models.CharField(choices=[('JANEIRO', 'Janeiro'), ('FEVEREIRO', 'Fevereiro'), ('MARÇO', 'Março'), ('ABRIL', 'Abril'), ('MAIO', 'Maio'), ('JUNHO', 'Junho'), ('JULHO', 'Julho'), ('AGOSTO', 'Agosto'), ('SETEMBRO', 'Setembro'), ('OUTUBRO', 'Outubro'), ('NOVEMBRO', 'Novembro'), ('DEZEMBRO', 'Dezembro')], help_text='Mês de referência', max_length=15)),
                ('lancamento', models.CharField(help_text='Descrição da transação', max_length=255)),
                ('categoria', models.CharField(help_text='Categoria original', max_length=100)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('CRÉDITO', 'Crédito'), ('DÉBITO', 'Débito')], help_text='Tipo de transação', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor monetário (positivo ou negativo)', max_digits=12)),
                ('fonte', models.CharField(help_text='Conta de origem (ex: Santander, Nubank)', max_length=100)),
                ('conta_final', models.CharField(help_text='Conta de destino (ex: Carteira, Poupança)', max_length=50)),
                ('pilar_tribalance', models.CharField(choices=[('NECESSIDADE', 'Necessidade'), ('CONFORTO & EXPERIÊNCIA', 'Conforto & Experiência'), ('CRESCIMENTO & LIBERDADE', 'Crescimento & Liberdade')], help_text='Pilar em que o lançamento se enquadra', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_meta', models.CharField(help_text='Nome da meta (aposentadoria, viagem...)', max_length=100)),
                ('valor_alvo', models.DecimalField(decimal_places=2, help_text='Valor total desejado', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prazo_anos', models.IntegerField(help_text='Prazo em anos para atingir a meta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, help_text='Aporte mensal recomendado', max_digits=12)),
                ('progresso', models.DecimalField(decimal_places=2, default=0, help_text='Percentual atingido (0–100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
            },
        ),
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pilar', models.CharField(choices=[('NECESSIDADE', 'Necessidade'), ('CONFORTO & EXPERIÊNCIA', 'Conforto & Experiência'), ('CRESCIMENTO & LIBERDADE', 'Crescimento & Liberdade')], max_length=50, unique=True)),
                ('percentual_ideal', models.DecimalField(decimal_places=2, help_text='Percentual ideal da renda para este pilar', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Mensal',
                'verbose_name_plural': 'Metas Mensais',
            },
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['data'], name='financeiro__data_5e6bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['mes'], name='financeiro__mes_b6b399_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['tipo'], name='financeiro__tipo_980071_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['pilar_tribalance'], name='financeiro__pilar_t_a62848_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['categoria'], name='financeiro__categor_53c9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['fonte'], name='financeiro__fonte_5918d8_idx'),
        ),
    ]
