# Generated by Django 4.2 on 2025-10-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lancamento',
            name='financeiro__mes_b6b399_idx',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='lancamento',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='mes',
        ),
    ]
