# Generated by Django 4.2 on 2025-10-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_remove_lancamento_financeiro__mes_b6b399_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='lancamento',
            field=models.CharField(default='Lançamento antigo', help_text='Descrição da transação', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lancamento',
            name='mes',
            field=models.CharField(choices=[('JANEIRO', 'Janeiro'), ('FEVEREIRO', 'Fevereiro'), ('MARÇO', 'Março'), ('ABRIL', 'Abril'), ('MAIO', 'Maio'), ('JUNHO', 'Junho'), ('JULHO', 'Julho'), ('AGOSTO', 'Agosto'), ('SETEMBRO', 'Setembro'), ('OUTUBRO', 'Outubro'), ('NOVEMBRO', 'Novembro'), ('DEZEMBRO', 'Dezembro')], default='Lançamento antigo', help_text='Mês de referência', max_length=15),
            preserve_default=False,
        ),
    ]
